name: issue_detection_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.4
  firebase_storage: ^11.7.6
  firebase_auth: ^4.20.0
  firebase_messaging: ^14.9.4

  # State Management (using flutter_bloc as an example)
  flutter_bloc: ^8.1.6

  # UI & Utility
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
